---
- name: Install docker python package
  become: yes
  pip:
    name: docker

- name: Install kubernetes python package
  pip:
    name: kubernetes

- name: Install Helm Diff Plugin
  kubernetes.core.helm_plugin:
    plugin_path: https://github.com/databus23/helm-diff
