---
- name: Install pip package
  when: ansible_distribution != "MacOSX"
  become: yes
  apt:
    update_cache: yes
    name: python3-pip

- name: Install docker python package
  become: yes
  pip:
    name: docker

- name: Install kubernetes and crypto python package
  pip:
    name: "{{ item }}"
  with_items:
    - kubernetes
    - cryptography
    - pyopenssl

- name: Install Helm Diff Plugin
  kubernetes.core.helm_plugin:
    plugin_path: https://github.com/databus23/helm-diff
