- name: Install Magma Orchestrator
  hosts: all

  roles:
  # - role: shubhamtatvamasi.magma.docker


  # - role: ../magma/roles/prerequisites
  # - role: ../magma/roles/docker
  # - role: ../magma/roles/kubernetes
  - role: ../magma/roles/postgresql
