- name: Install MetallLB
  kubernetes.core.helm:
    name: metallb
    chart_ref: metallb/metallb
    release_namespace: "{{ metallb_namespace }}"
    create_namespace: true
    values:
      configInline: 
        address-pools:
        - name: default
          protocol: layer2
          addresses:
          - "{{ ansible_host }}/32"
