- name: Install MetallLB
  kubernetes.core.helm:
    name: metallb
    chart_ref: metallb/metallb
    release_namespace: metallb-system
    create_namespace: true
    values:
      configInline: 
        address-pools:
        - name: default
          protocol: layer2
          addresses:
          - "{{ ansible_host }}/32"
          # - "{{ ip_1 }}/32"
          # - "{{ ip_2 }}/32"
          # - "{{ ip_3 }}/32"
          # - "{{ ip_4 }}/32"
          # - "{{ ip_5 }}/32"
