- name: Install MetallLB
  kubernetes.core.helm:
    name: metallb
    chart_ref: metallb/metallb
    release_namespace: metallb-system
    create_namespace: true
    values:
      configInline: 
        address-pools:
        - name: default
          protocol: layer2
          addresses:
          - "{{ ip_pool }}"
